/**
 * WildAtlas - Regional Fauna Reference Catalog
 * Deterministic regional biodiversity reference for ensuring rich biodiversity across all biomes
 * Derived from authenticated GBIF & IUCN Red List biodiversity baselines.
 */

export const REGIONAL_FAUNA_CATALOG = {
  Asia: [
    // Mammals (>=15 species)
    { name: 'Bengal Tiger', sci: 'Panthera tigris', group: 'Mammal', iucn: 'EN', gbif_key: '5219426', order: 'Carnivora', family: 'Felidae', diet: 'Carnivore' },
    { name: 'Asian Elephant', sci: 'Elephas maximus', group: 'Mammal', iucn: 'EN', gbif_key: '5219743', order: 'Proboscidea', family: 'Elephantidae', diet: 'Herbivore' },
    { name: 'Indian Leopard', sci: 'Panthera pardus fusca', group: 'Mammal', iucn: 'VU', gbif_key: '5219434', order: 'Carnivora', family: 'Felidae', diet: 'Carnivore' },
    { name: 'Indian Rhinoceros', sci: 'Rhinoceros unicornis', group: 'Mammal', iucn: 'VU', gbif_key: '2440939', order: 'Perissodactyla', family: 'Rhinocerotidae', diet: 'Herbivore' },
    { name: 'Sloth Bear', sci: 'Melursus ursinus', group: 'Mammal', iucn: 'VU', gbif_key: '2433434', order: 'Carnivora', family: 'Ursidae', diet: 'Omnivore' },
    { name: 'Gaur', sci: 'Bos gaurus', group: 'Mammal', iucn: 'VU', gbif_key: '2441029', order: 'Artiodactyla', family: 'Bovidae', diet: 'Herbivore' },
    { name: 'Dhole (Asiatic Wild Dog)', sci: 'Cuon alpinus', group: 'Mammal', iucn: 'EN', gbif_key: '2434547', order: 'Carnivora', family: 'Canidae', diet: 'Carnivore' },
    { name: 'Sambar Deer', sci: 'Rusa unicolor', group: 'Mammal', iucn: 'VU', gbif_key: '5220138', order: 'Artiodactyla', family: 'Cervidae', diet: 'Herbivore' },
    { name: 'Chital (Spotted Deer)', sci: 'Axis axis', group: 'Mammal', iucn: 'LC', gbif_key: '2440927', order: 'Artiodactyla', family: 'Cervidae', diet: 'Herbivore' },
    { name: 'Indian Muntjac (Barking Deer)', sci: 'Muntiacus muntjak', group: 'Mammal', iucn: 'LC', gbif_key: '2440947', order: 'Artiodactyla', family: 'Cervidae', diet: 'Herbivore' },
    { name: 'Nilgai (Blue Bull)', sci: 'Boselaphus tragocamelus', group: 'Mammal', iucn: 'LC', gbif_key: '2441088', order: 'Artiodactyla', family: 'Bovidae', diet: 'Herbivore' },
    { name: 'Wild Boar', sci: 'Sus scrofa', group: 'Mammal', iucn: 'LC', gbif_key: '2441214', order: 'Artiodactyla', family: 'Suidae', diet: 'Omnivore' },
    { name: 'Rhesus Macaque', sci: 'Macaca mulatta', group: 'Mammal', iucn: 'LC', gbif_key: '2436615', order: 'Primates', family: 'Cercopithecidae', diet: 'Omnivore' },
    { name: 'Gray Langur', sci: 'Semnopithecus entellus', group: 'Mammal', iucn: 'LC', gbif_key: '2436573', order: 'Primates', family: 'Cercopithecidae', diet: 'Herbivore' },
    { name: 'Indian Giant Flying Squirrel', sci: 'Petaurista philippensis', group: 'Mammal', iucn: 'LC', gbif_key: '2437255', order: 'Rodentia', family: 'Sciuridae', diet: 'Herbivore' },
    { name: 'Asian Palm Civet', sci: 'Paradoxurus hermaphroditus', group: 'Mammal', iucn: 'LC', gbif_key: '2434658', order: 'Carnivora', family: 'Viverridae', diet: 'Omnivore' },

    // Birds (>=25 species)
    { name: 'Indian Peafowl', sci: 'Pavo cristatus', group: 'Bird', iucn: 'LC', gbif_key: '2474136', order: 'Galliformes', family: 'Phasianidae', diet: 'Omnivore' },
    { name: 'Great Hornbill', sci: 'Buceros bicornis', group: 'Bird', iucn: 'VU', gbif_key: '2475476', order: 'Bucerotiformes', family: 'Bucerotidae', diet: 'Frugivore' },
    { name: 'White-throated Kingfisher', sci: 'Halcyon smyrnensis', group: 'Bird', iucn: 'LC', gbif_key: '2475628', order: 'Coraciiformes', family: 'Alcedinidae', diet: 'Carnivore' },
    { name: 'Black Kite', sci: 'Milvus migrans', group: 'Bird', iucn: 'LC', gbif_key: '2480556', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'Crested Serpent Eagle', sci: 'Spilornis cheela', group: 'Bird', iucn: 'LC', gbif_key: '2480398', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'Changeable Hawk-Eagle', sci: 'Nisaetus cirrhatus', group: 'Bird', iucn: 'LC', gbif_key: '5844436', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'Green Imperial Pigeon', sci: 'Ducula aenea', group: 'Bird', iucn: 'LC', gbif_key: '2495914', order: 'Columbiformes', family: 'Columbidae', diet: 'Frugivore' },
    { name: 'Asian Koel', sci: 'Eudynamys scolopaceus', group: 'Bird', iucn: 'LC', gbif_key: '2496291', order: 'Cuculiformes', family: 'Cuculidae', diet: 'Omnivore' },
    { name: 'Greater Coucal', sci: 'Centropus sinensis', group: 'Bird', iucn: 'LC', gbif_key: '2496353', order: 'Cuculiformes', family: 'Cuculidae', diet: 'Carnivore' },
    { name: 'Spotted Owlet', sci: 'Athene brama', group: 'Bird', iucn: 'LC', gbif_key: '2497274', order: 'Strigiformes', family: 'Strigidae', diet: 'Carnivore' },
    { name: 'Brown Fish Owl', sci: 'Ketupa zeylonensis', group: 'Bird', iucn: 'LC', gbif_key: '2497746', order: 'Strigiformes', family: 'Strigidae', diet: 'Carnivore' },
    { name: 'Indian Roller', sci: 'Coracias benghalensis', group: 'Bird', iucn: 'LC', gbif_key: '2475736', order: 'Coraciiformes', family: 'Coraciidae', diet: 'Insectivore' },
    { name: 'Coppersmith Barbet', sci: 'Psilopogon haemacephalus', group: 'Bird', iucn: 'LC', gbif_key: '8220023', order: 'Piciformes', family: 'Megalaimidae', diet: 'Frugivore' },
    { name: 'Black-rumped Flameback', sci: 'Dinopium benghalense', group: 'Bird', iucn: 'LC', gbif_key: '2477983', order: 'Piciformes', family: 'Picidae', diet: 'Insectivore' },
    { name: 'Red-vented Bulbul', sci: 'Pycnonotus cafer', group: 'Bird', iucn: 'LC', gbif_key: '2486128', order: 'Passeriformes', family: 'Pycnonotidae', diet: 'Frugivore' },
    { name: 'Oriental Magpie-Robin', sci: 'Copsychus saularis', group: 'Bird', iucn: 'LC', gbif_key: '2492576', order: 'Passeriformes', family: 'Muscicapidae', diet: 'Insectivore' },
    { name: 'Rufous Treepie', sci: 'Dendrocitta vagabunda', group: 'Bird', iucn: 'LC', gbif_key: '2482438', order: 'Passeriformes', family: 'Corvidae', diet: 'Omnivore' },
    { name: 'Greater Racket-tailed Drongo', sci: 'Dicrurus paradiseus', group: 'Bird', iucn: 'LC', gbif_key: '2494634', order: 'Passeriformes', family: 'Dicruridae', diet: 'Insectivore' },
    { name: 'Jungle Babbler', sci: 'Argya striata', group: 'Bird', iucn: 'LC', gbif_key: '10746944', order: 'Passeriformes', family: 'Leiothrichidae', diet: 'Insectivore' },
    { name: 'Purple Sunbird', sci: 'Cinnyris asiaticus', group: 'Bird', iucn: 'LC', gbif_key: '6100918', order: 'Passeriformes', family: 'Nectariniidae', diet: 'Nectarivore' },
    { name: 'Rose-ringed Parakeet', sci: 'Psittacula krameri', group: 'Bird', iucn: 'LC', gbif_key: '5229064', order: 'Psittaciformes', family: 'Psittaculidae', diet: 'Granivore' },
    { name: 'Plum-headed Parakeet', sci: 'Himalayapsitta cyanocephala', group: 'Bird', iucn: 'LC', gbif_key: '10714201', order: 'Psittaciformes', family: 'Psittaculidae', diet: 'Granivore' },
    { name: 'Asian Fairy-bluebird', sci: 'Irena puella', group: 'Bird', iucn: 'LC', gbif_key: '2488887', order: 'Passeriformes', family: 'Irenidae', diet: 'Frugivore' },
    { name: 'White-bellied Woodpecker', sci: 'Dryocopus javensis', group: 'Bird', iucn: 'LC', gbif_key: '2477839', order: 'Piciformes', family: 'Picidae', diet: 'Insectivore' },
    { name: 'Malabar Pied Hornbill', sci: 'Anthracoceros coronatus', group: 'Bird', iucn: 'NT', gbif_key: '2475459', order: 'Bucerotiformes', family: 'Bucerotidae', diet: 'Frugivore' },

    // Reptiles (>=18 species)
    { name: 'King Cobra', sci: 'Ophiophagus hannah', group: 'Reptile', iucn: 'VU', gbif_key: '2470659', order: 'Squamata', family: 'Elapidae', diet: 'Carnivore' },
    { name: 'Indian Python', sci: 'Python molurus', group: 'Reptile', iucn: 'NT', gbif_key: '2464972', order: 'Squamata', family: 'Pythonidae', diet: 'Carnivore' },
    { name: 'Spectacled Cobra', sci: 'Naja naja', group: 'Reptile', iucn: 'LC', gbif_key: '2470327', order: 'Squamata', family: 'Elapidae', diet: 'Carnivore' },
    { name: "Russell's Viper", sci: 'Daboia russelii', group: 'Reptile', iucn: 'LC', gbif_key: '2470764', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'Common Krait', sci: 'Bungarus caeruleus', group: 'Reptile', iucn: 'LC', gbif_key: '2470404', order: 'Squamata', family: 'Elapidae', diet: 'Carnivore' },
    { name: 'Saw-scaled Viper', sci: 'Echis carinatus', group: 'Reptile', iucn: 'LC', gbif_key: '2470776', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'Bengal Monitor', sci: 'Varanus bengalensis', group: 'Reptile', iucn: 'LC', gbif_key: '2470817', order: 'Squamata', family: 'Varanidae', diet: 'Carnivore' },
    { name: 'Water Monitor', sci: 'Varanus salvator', group: 'Reptile', iucn: 'LC', gbif_key: '2470818', order: 'Squamata', family: 'Varanidae', diet: 'Carnivore' },
    { name: 'Oriental Garden Lizard', sci: 'Calotes versicolor', group: 'Reptile', iucn: 'LC', gbif_key: '2465352', order: 'Squamata', family: 'Agamidae', diet: 'Insectivore' },
    { name: 'Tokay Gecko', sci: 'Gekko gecko', group: 'Reptile', iucn: 'LC', gbif_key: '2468307', order: 'Squamata', family: 'Gekkonidae', diet: 'Insectivore' },
    { name: 'Brook’s House Gecko', sci: 'Hemidactylus brookii', group: 'Reptile', iucn: 'LC', gbif_key: '2468087', order: 'Squamata', family: 'Gekkonidae', diet: 'Insectivore' },
    { name: 'Indian Chameleon', sci: 'Chamaeleo zeylanicus', group: 'Reptile', iucn: 'LC', gbif_key: '2465492', order: 'Squamata', family: 'Chamaeleonidae', diet: 'Insectivore' },
    { name: 'Checkered Keelback', sci: 'Fowlea piscator', group: 'Reptile', iucn: 'LC', gbif_key: '9603513', order: 'Squamata', family: 'Colubridae', diet: 'Piscivore' },
    { name: 'Indian Rat Snake', sci: 'Ptyas mucosa', group: 'Reptile', iucn: 'LC', gbif_key: '2456488', order: 'Squamata', family: 'Colubridae', diet: 'Carnivore' },
    { name: 'Green Vine Snake', sci: 'Ahaetulla nasuta', group: 'Reptile', iucn: 'LC', gbif_key: '2454668', order: 'Squamata', family: 'Colubridae', diet: 'Carnivore' },
    { name: 'Indian Star Tortoise', sci: 'Geochelone elegans', group: 'Reptile', iucn: 'VU', gbif_key: '2441865', order: 'Testudines', family: 'Testudinidae', diet: 'Herbivore' },
    { name: 'Mugger Crocodile', sci: 'Crocodylus palustris', group: 'Reptile', iucn: 'VU', gbif_key: '2441416', order: 'Crocodylia', family: 'Crocodylidae', diet: 'Carnivore' },
    { name: 'Gharial', sci: 'Gavialis gangeticus', group: 'Reptile', iucn: 'CR', gbif_key: '2441398', order: 'Crocodylia', family: 'Gavialidae', diet: 'Piscivore' }
  ],

  Africa: [
    // Mammals (>=15 species)
    { name: 'African Bush Elephant', sci: 'Loxodonta africana', group: 'Mammal', iucn: 'EN', gbif_key: '5219741', order: 'Proboscidea', family: 'Elephantidae', diet: 'Herbivore' },
    { name: 'Lion', sci: 'Panthera leo', group: 'Mammal', iucn: 'VU', gbif_key: '5219436', order: 'Carnivora', family: 'Felidae', diet: 'Carnivore' },
    { name: 'African Leopard', sci: 'Panthera pardus pardus', group: 'Mammal', iucn: 'VU', gbif_key: '5219434', order: 'Carnivora', family: 'Felidae', diet: 'Carnivore' },
    { name: 'Cheetah', sci: 'Acinonyx jubatus', group: 'Mammal', iucn: 'VU', gbif_key: '2435035', order: 'Carnivora', family: 'Felidae', diet: 'Carnivore' },
    { name: 'Giraffe', sci: 'Giraffa camelopardalis', group: 'Mammal', iucn: 'VU', gbif_key: '2441208', order: 'Artiodactyla', family: 'Giraffidae', diet: 'Herbivore' },
    { name: 'Hippopotamus', sci: 'Hippopotamus amphibius', group: 'Mammal', iucn: 'VU', gbif_key: '2441198', order: 'Artiodactyla', family: 'Hippopotamidae', diet: 'Herbivore' },
    { name: 'African Buffalo', sci: 'Syncerus caffer', group: 'Mammal', iucn: 'NT', gbif_key: '2441042', order: 'Artiodactyla', family: 'Bovidae', diet: 'Herbivore' },
    { name: 'Spotted Hyena', sci: 'Crocuta crocuta', group: 'Mammal', iucn: 'LC', gbif_key: '2434526', order: 'Carnivora', family: 'Hyaenidae', diet: 'Carnivore' },
    { name: 'Plains Zebra', sci: 'Equus quagga', group: 'Mammal', iucn: 'NT', gbif_key: '2440892', order: 'Perissodactyla', family: 'Equidae', diet: 'Herbivore' },
    { name: 'Chimpanzee', sci: 'Pan troglodytes', group: 'Mammal', iucn: 'EN', gbif_key: '2436440', order: 'Primates', family: 'Hominidae', diet: 'Omnivore' },
    { name: 'Western Lowland Gorilla', sci: 'Gorilla gorilla', group: 'Mammal', iucn: 'CR', gbif_key: '2436444', order: 'Primates', family: 'Hominidae', diet: 'Herbivore' },
    { name: 'Warthog', sci: 'Phacochoerus africanus', group: 'Mammal', iucn: 'LC', gbif_key: '2441221', order: 'Artiodactyla', family: 'Suidae', diet: 'Herbivore' },
    { name: 'Black Rhinoceros', sci: 'Diceros bicornis', group: 'Mammal', iucn: 'CR', gbif_key: '2440934', order: 'Perissodactyla', family: 'Rhinocerotidae', diet: 'Herbivore' },
    { name: 'African Wild Dog', sci: 'Lycaon pictus', group: 'Mammal', iucn: 'EN', gbif_key: '2434552', order: 'Carnivora', family: 'Canidae', diet: 'Carnivore' },
    { name: 'Chacma Baboon', sci: 'Papio ursinus', group: 'Mammal', iucn: 'LC', gbif_key: '2436474', order: 'Primates', family: 'Cercopithecidae', diet: 'Omnivore' },
    { name: 'Vervet Monkey', sci: 'Chlorocebus pygerythrus', group: 'Mammal', iucn: 'LC', gbif_key: '2436537', order: 'Primates', family: 'Cercopithecidae', diet: 'Herbivore' },

    // Birds (>=25 species)
    { name: 'African Fish Eagle', sci: 'Haliaeetus vocifer', group: 'Bird', iucn: 'LC', gbif_key: '2480447', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Piscivore' },
    { name: 'Martial Eagle', sci: 'Polemaetus bellicosus', group: 'Bird', iucn: 'EN', gbif_key: '2480370', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'Bateleur', sci: 'Terathopius ecaudatus', group: 'Bird', iucn: 'EN', gbif_key: '2480538', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'Secretarybird', sci: 'Sagittarius serpentarius', group: 'Bird', iucn: 'EN', gbif_key: '2480749', order: 'Accipitriformes', family: 'Sagittariidae', diet: 'Carnivore' },
    { name: 'Grey Crowned Crane', sci: 'Balearica regulorum', group: 'Bird', iucn: 'EN', gbif_key: '2474955', order: 'Gruiformes', family: 'Gruidae', diet: 'Omnivore' },
    { name: 'Saddle-billed Stork', sci: 'Ephippiorhynchus senegalensis', group: 'Bird', iucn: 'LC', gbif_key: '2481928', order: 'Ciconiiformes', family: 'Ciconiidae', diet: 'Carnivore' },
    { name: 'African Grey Parrot', sci: 'Psittacus erithacus', group: 'Bird', iucn: 'EN', gbif_key: '2479509', order: 'Psittaciformes', family: 'Psittacidae', diet: 'Frugivore' },
    { name: 'Lilac-breasted Roller', sci: 'Coracias caudatus', group: 'Bird', iucn: 'LC', gbif_key: '2475742', order: 'Coraciiformes', family: 'Coraciidae', diet: 'Insectivore' },
    { name: 'Southern Ground Hornbill', sci: 'Bucorvus leadbeateri', group: 'Bird', iucn: 'VU', gbif_key: '2475442', order: 'Bucerotiformes', family: 'Bucorvidae', diet: 'Carnivore' },
    { name: 'Silvery-cheeked Hornbill', sci: 'Bycanistes brevis', group: 'Bird', iucn: 'LC', gbif_key: '2475463', order: 'Bucerotiformes', family: 'Bucerotidae', diet: 'Frugivore' },
    { name: "Meyer's Parrot", sci: 'Poicephalus meyeri', group: 'Bird', iucn: 'LC', gbif_key: '2479603', order: 'Psittaciformes', family: 'Psittacidae', diet: 'Frugivore' },
    { name: "Schalow's Turaco", sci: 'Tauraco schalowi', group: 'Bird', iucn: 'LC', gbif_key: '2475245', order: 'Musophagiformes', family: 'Musophagidae', diet: 'Frugivore' },
    { name: 'Great Blue Turaco', sci: 'Corythaeola cristata', group: 'Bird', iucn: 'LC', gbif_key: '2475225', order: 'Musophagiformes', family: 'Musophagidae', diet: 'Frugivore' },
    { name: 'African Emerald Cuckoo', sci: 'Chrysococcyx cupreus', group: 'Bird', iucn: 'LC', gbif_key: '2496338', order: 'Cuculiformes', family: 'Cuculidae', diet: 'Insectivore' },
    { name: 'Malachite Kingfisher', sci: 'Corythornis cristatus', group: 'Bird', iucn: 'LC', gbif_key: '7341880', order: 'Coraciiformes', family: 'Alcedinidae', diet: 'Piscivore' },
    { name: 'Woodland Kingfisher', sci: 'Halcyon senegalensis', group: 'Bird', iucn: 'LC', gbif_key: '2475620', order: 'Coraciiformes', family: 'Alcedinidae', diet: 'Carnivore' },
    { name: 'Pied Kingfisher', sci: 'Ceryle rudis', group: 'Bird', iucn: 'LC', gbif_key: '2475497', order: 'Coraciiformes', family: 'Alcedinidae', diet: 'Piscivore' },
    { name: 'African Paradise Flycatcher', sci: 'Terpsiphone viridis', group: 'Bird', iucn: 'LC', gbif_key: '2486701', order: 'Passeriformes', family: 'Monarchidae', diet: 'Insectivore' },
    { name: 'Superb Starling', sci: 'Lamprotornis superbus', group: 'Bird', iucn: 'LC', gbif_key: '2489063', order: 'Passeriformes', family: 'Sturnidae', diet: 'Omnivore' },
    { name: 'Red-billed Oxpecker', sci: 'Buphagus erythrorynchus', group: 'Bird', iucn: 'LC', gbif_key: '2489018', order: 'Passeriformes', family: 'Buphagidae', diet: 'Insectivore' },
    { name: 'African Openbill', sci: 'Anastomus lamelligerus', group: 'Bird', iucn: 'LC', gbif_key: '2481919', order: 'Ciconiiformes', family: 'Ciconiidae', diet: 'Molluscivore' },
    { name: 'Goliath Heron', sci: 'Ardea goliath', group: 'Bird', iucn: 'LC', gbif_key: '2480939', order: 'Pelecaniformes', family: 'Ardeidae', diet: 'Piscivore' },
    { name: 'Hamerkop', sci: 'Scopus umbretta', group: 'Bird', iucn: 'LC', gbif_key: '2481915', order: 'Pelecaniformes', family: 'Scopidae', diet: 'Carnivore' },
    { name: 'Hadada Ibis', sci: 'Bostrychia hagedash', group: 'Bird', iucn: 'LC', gbif_key: '2480789', order: 'Pelecaniformes', family: 'Threskiornithidae', diet: 'Invertebrates' },
    { name: 'Narina Trogon', sci: 'Apaloderma narina', group: 'Bird', iucn: 'LC', gbif_key: '2496639', order: 'Trogoniformes', family: 'Trogonidae', diet: 'Insectivore' },

    // Reptiles (>=18 species)
    { name: 'Nile Crocodile', sci: 'Crocodylus niloticus', group: 'Reptile', iucn: 'LC', gbif_key: '2441411', order: 'Crocodylia', family: 'Crocodylidae', diet: 'Carnivore' },
    { name: 'Black Mamba', sci: 'Dendroaspis polylepis', group: 'Reptile', iucn: 'LC', gbif_key: '2470183', order: 'Squamata', family: 'Elapidae', diet: 'Carnivore' },
    { name: 'Green Mamba', sci: 'Dendroaspis angusticeps', group: 'Reptile', iucn: 'LC', gbif_key: '2470186', order: 'Squamata', family: 'Elapidae', diet: 'Carnivore' },
    { name: 'Puff Adder', sci: 'Bitis arietans', group: 'Reptile', iucn: 'LC', gbif_key: '2470617', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'Gaboon Viper', sci: 'Bitis gabonica', group: 'Reptile', iucn: 'VU', gbif_key: '2470616', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'Rhinoceros Viper', sci: 'Bitis nasicornis', group: 'Reptile', iucn: 'LC', gbif_key: '2470624', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'African Rock Python', sci: 'Python sebae', group: 'Reptile', iucn: 'NT', gbif_key: '2464977', order: 'Squamata', family: 'Pythonidae', diet: 'Carnivore' },
    { name: 'Boomslang', sci: 'Dispholidus typus', group: 'Reptile', iucn: 'LC', gbif_key: '2456424', order: 'Squamata', family: 'Colubridae', diet: 'Carnivore' },
    { name: 'Nile Monitor', sci: 'Varanus niloticus', group: 'Reptile', iucn: 'LC', gbif_key: '2470819', order: 'Squamata', family: 'Varanidae', diet: 'Carnivore' },
    { name: 'Rock Monitor', sci: 'Varanus albigularis', group: 'Reptile', iucn: 'LC', gbif_key: '2470824', order: 'Squamata', family: 'Varanidae', diet: 'Carnivore' },
    { name: 'Leopard Tortoise', sci: 'Stigmochelys pardalis', group: 'Reptile', iucn: 'LC', gbif_key: '5789498', order: 'Testudines', family: 'Testudinidae', diet: 'Herbivore' },
    { name: 'Bell’s Hinge-back Tortoise', sci: 'Kinixys belliana', group: 'Reptile', iucn: 'LC', gbif_key: '2441771', order: 'Testudines', family: 'Testudinidae', diet: 'Herbivore' },
    { name: 'Flap-necked Chameleon', sci: 'Chamaeleo dilepis', group: 'Reptile', iucn: 'LC', gbif_key: '2465494', order: 'Squamata', family: 'Chamaeleonidae', diet: 'Insectivore' },
    { name: 'Jackson’s Chameleon', sci: 'Trioceros jacksonii', group: 'Reptile', iucn: 'LC', gbif_key: '5789578', order: 'Squamata', family: 'Chamaeleonidae', diet: 'Insectivore' },
    { name: 'Red-headed Rock Agama', sci: 'Agama agama', group: 'Reptile', iucn: 'LC', gbif_key: '2465809', order: 'Squamata', family: 'Agamidae', diet: 'Insectivore' },
    { name: 'Cape Cobra', sci: 'Naja nivea', group: 'Reptile', iucn: 'LC', gbif_key: '2470335', order: 'Squamata', family: 'Elapidae', diet: 'Carnivore' },
    { name: 'Forest Cobra', sci: 'Naja melanoleuca', group: 'Reptile', iucn: 'LC', gbif_key: '2470337', order: 'Squamata', family: 'Elapidae', diet: 'Carnivore' },
    { name: 'Twig Snake (Vine Snake)', sci: 'Thelotornis capensis', group: 'Reptile', iucn: 'LC', gbif_key: '2456428', order: 'Squamata', family: 'Colubridae', diet: 'Carnivore' }
  ],

  'South America': [
    // Mammals (>=15 species)
    { name: 'Jaguar', sci: 'Panthera onca', group: 'Mammal', iucn: 'NT', gbif_key: '5219429', order: 'Carnivora', family: 'Felidae', diet: 'Carnivore' },
    { name: 'South American Tapir', sci: 'Tapirus terrestris', group: 'Mammal', iucn: 'VU', gbif_key: '2440898', order: 'Perissodactyla', family: 'Tapiridae', diet: 'Herbivore' },
    { name: 'Giant Anteater', sci: 'Myrmecophaga tridactyla', group: 'Mammal', iucn: 'VU', gbif_key: '2436340', order: 'Pilosa', family: 'Myrmecophagidae', diet: 'Insectivore' },
    { name: 'Giant Armadillo', sci: 'Priodontes maximus', group: 'Mammal', iucn: 'VU', gbif_key: '2440798', order: 'Cingulata', family: 'Chlamyphoridae', diet: 'Insectivore' },
    { name: 'Giant Otter', sci: 'Pteronura brasiliensis', group: 'Mammal', iucn: 'EN', gbif_key: '2433644', order: 'Carnivora', family: 'Mustelidae', diet: 'Piscivore' },
    { name: 'Capybara', sci: 'Hydrochoerus hydrochaeris', group: 'Mammal', iucn: 'LC', gbif_key: '2437648', order: 'Rodentia', family: 'Caviidae', diet: 'Herbivore' },
    { name: 'Ocelot', sci: 'Leopardus pardalis', group: 'Mammal', iucn: 'LC', gbif_key: '2435242', order: 'Carnivora', family: 'Felidae', diet: 'Carnivore' },
    { name: 'Puma (Cougar)', sci: 'Puma concolor', group: 'Mammal', iucn: 'LC', gbif_key: '2435099', order: 'Carnivora', family: 'Felidae', diet: 'Carnivore' },
    { name: 'Brown-throated Sloth', sci: 'Bradypus variegatus', group: 'Mammal', iucn: 'LC', gbif_key: '2436353', order: 'Pilosa', family: 'Bradypodidae', diet: 'Folivore' },
    { name: 'Linnaeus’s Two-toed Sloth', sci: 'Choloepus didactylus', group: 'Mammal', iucn: 'LC', gbif_key: '2436361', order: 'Pilosa', family: 'Choloepodidae', diet: 'Folivore' },
    { name: 'Black Howler Monkey', sci: 'Alouatta caraya', group: 'Mammal', iucn: 'NT', gbif_key: '2436665', order: 'Primates', family: 'Atelidae', diet: 'Herbivore' },
    { name: 'Tufted Capuchin', sci: 'Sapajus apella', group: 'Mammal', iucn: 'LC', gbif_key: '7412702', order: 'Primates', family: 'Cebidae', diet: 'Omnivore' },
    { name: 'Golden Lion Tamarin', sci: 'Leontopithecus rosalia', group: 'Mammal', iucn: 'EN', gbif_key: '2436494', order: 'Primates', family: 'Callitrichidae', diet: 'Omnivore' },
    { name: 'Red-handed Tamarin', sci: 'Saguinus midas', group: 'Mammal', iucn: 'LC', gbif_key: '5219502', order: 'Primates', family: 'Callitrichidae', diet: 'Omnivore' },
    { name: 'Collared Peccary', sci: 'Pecari tajacu', group: 'Mammal', iucn: 'LC', gbif_key: '2441235', order: 'Artiodactyla', family: 'Tayassuidae', diet: 'Herbivore' },
    { name: 'Red Brocket Deer', sci: 'Mazama americana', group: 'Mammal', iucn: 'DD', gbif_key: '2440960', order: 'Artiodactyla', family: 'Cervidae', diet: 'Herbivore' },

    // Birds (>=25 species)
    { name: 'Harpy Eagle', sci: 'Harpia harpyja', group: 'Bird', iucn: 'VU', gbif_key: '2480436', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'Toco Toucan', sci: 'Ramphastos toco', group: 'Bird', iucn: 'LC', gbif_key: '2478802', order: 'Piciformes', family: 'Ramphastidae', diet: 'Frugivore' },
    { name: 'Keel-billed Toucan', sci: 'Ramphastos sulfuratus', group: 'Bird', iucn: 'NT', gbif_key: '2478800', order: 'Piciformes', family: 'Ramphastidae', diet: 'Frugivore' },
    { name: 'Scarlet Macaw', sci: 'Ara macao', group: 'Bird', iucn: 'LC', gbif_key: '2479374', order: 'Psittaciformes', family: 'Psittacidae', diet: 'Granivore' },
    { name: 'Blue-and-yellow Macaw', sci: 'Ara ararauna', group: 'Bird', iucn: 'LC', gbif_key: '2479379', order: 'Psittaciformes', family: 'Psittacidae', diet: 'Granivore' },
    { name: 'Hyacinth Macaw', sci: 'Anodorhynchus hyacinthinus', group: 'Bird', iucn: 'VU', gbif_key: '2479366', order: 'Psittaciformes', family: 'Psittacidae', diet: 'Granivore' },
    { name: 'Guianan Cock-of-the-rock', sci: 'Rupicola rupicola', group: 'Bird', iucn: 'LC', gbif_key: '2486749', order: 'Passeriformes', family: 'Cotingidae', diet: 'Frugivore' },
    { name: 'Andean Cock-of-the-rock', sci: 'Rupicola peruvianus', group: 'Bird', iucn: 'LC', gbif_key: '2486751', order: 'Passeriformes', family: 'Cotingidae', diet: 'Frugivore' },
    { name: 'Sunbittern', sci: 'Eurypyga helias', group: 'Bird', iucn: 'LC', gbif_key: '2474349', order: 'Eurypygiformes', family: 'Eurypygidae', diet: 'Carnivore' },
    { name: 'Jabiru Stork', sci: 'Jabiru mycteria', group: 'Bird', iucn: 'LC', gbif_key: '2481926', order: 'Ciconiiformes', family: 'Ciconiidae', diet: 'Carnivore' },
    { name: 'Hoatzin', sci: 'Opisthocomus hoazin', group: 'Bird', iucn: 'LC', gbif_key: '2475220', order: 'Opisthocomiformes', family: 'Opisthocomidae', diet: 'Folivore' },
    { name: 'King Vulture', sci: 'Sarcoramphus papa', group: 'Bird', iucn: 'LC', gbif_key: '2480654', order: 'Cathartiformes', family: 'Cathartidae', diet: 'Scavenger' },
    { name: 'Andean Condor', sci: 'Vultur gryphus', group: 'Bird', iucn: 'VU', gbif_key: '2480651', order: 'Cathartiformes', family: 'Cathartidae', diet: 'Scavenger' },
    { name: 'Rufous Motmot', sci: 'Baryphthengus martii', group: 'Bird', iucn: 'LC', gbif_key: '2475306', order: 'Coraciiformes', family: 'Momotidae', diet: 'Omnivore' },
    { name: 'Amazonian Motmot', sci: 'Momotus momota', group: 'Bird', iucn: 'LC', gbif_key: '2475317', order: 'Coraciiformes', family: 'Momotidae', diet: 'Omnivore' },
    { name: 'Crimson-crested Woodpecker', sci: 'Campephilus melanoleucos', group: 'Bird', iucn: 'LC', gbif_key: '2477884', order: 'Piciformes', family: 'Picidae', diet: 'Insectivore' },
    { name: 'Swallow-tailed Kite', sci: 'Elanoides forficatus', group: 'Bird', iucn: 'LC', gbif_key: '2480572', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'Screaming Piha', sci: 'Lipaugus vociferans', group: 'Bird', iucn: 'LC', gbif_key: '2486744', order: 'Passeriformes', family: 'Cotingidae', diet: 'Frugivore' },
    { name: 'Paradise Tanager', sci: 'Tangara chilensis', group: 'Bird', iucn: 'LC', gbif_key: '2488344', order: 'Passeriformes', family: 'Thraupidae', diet: 'Frugivore' },
    { name: 'Green Honeycreeper', sci: 'Chlorophanes spiza', group: 'Bird', iucn: 'LC', gbif_key: '2488494', order: 'Passeriformes', family: 'Thraupidae', diet: 'Nectarivore' },
    { name: 'Red-legged Honeycreeper', sci: 'Cyanerpes cyaneus', group: 'Bird', iucn: 'LC', gbif_key: '2488498', order: 'Passeriformes', family: 'Thraupidae', diet: 'Nectarivore' },
    { name: 'Channel-billed Toucan', sci: 'Ramphastos vitellinus', group: 'Bird', iucn: 'VU', gbif_key: '2478796', order: 'Piciformes', family: 'Ramphastidae', diet: 'Frugivore' },
    { name: 'Mealy Amazon', sci: 'Amazona farinosa', group: 'Bird', iucn: 'NT', gbif_key: '2479633', order: 'Psittaciformes', family: 'Psittacidae', diet: 'Frugivore' },
    { name: 'Capped Heron', sci: 'Pilherodius pileatus', group: 'Bird', iucn: 'LC', gbif_key: '2480927', order: 'Pelecaniformes', family: 'Ardeidae', diet: 'Piscivore' },
    { name: 'Rufescent Tiger Heron', sci: 'Tigrisoma lineatum', group: 'Bird', iucn: 'LC', gbif_key: '2480838', order: 'Pelecaniformes', family: 'Ardeidae', diet: 'Carnivore' },

    // Reptiles (>=18 species)
    { name: 'Green Anaconda', sci: 'Eunectes murinus', group: 'Reptile', iucn: 'LC', gbif_key: '2465005', order: 'Squamata', family: 'Boidae', diet: 'Carnivore' },
    { name: 'Boa Constrictor', sci: 'Boa constrictor', group: 'Reptile', iucn: 'LC', gbif_key: '2465022', order: 'Squamata', family: 'Boidae', diet: 'Carnivore' },
    { name: 'Emerald Tree Boa', sci: 'Corallus caninus', group: 'Reptile', iucn: 'LC', gbif_key: '2465032', order: 'Squamata', family: 'Boidae', diet: 'Carnivore' },
    { name: 'Rainbow Boa', sci: 'Epicrates cenchria', group: 'Reptile', iucn: 'LC', gbif_key: '2465011', order: 'Squamata', family: 'Boidae', diet: 'Carnivore' },
    { name: 'Bushmaster', sci: 'Lachesis muta', group: 'Reptile', iucn: 'LC', gbif_key: '2470701', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'Fer-de-Lance (Jararaca)', sci: 'Bothrops atrox', group: 'Reptile', iucn: 'LC', gbif_key: '2470728', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'South American Rattlesnake', sci: 'Crotalus durissus', group: 'Reptile', iucn: 'LC', gbif_key: '2470678', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'Green Iguana', sci: 'Iguana iguana', group: 'Reptile', iucn: 'LC', gbif_key: '2465380', order: 'Squamata', family: 'Iguanidae', diet: 'Herbivore' },
    { name: 'Black Caiman', sci: 'Melanosuchus niger', group: 'Reptile', iucn: 'LC', gbif_key: '2441438', order: 'Crocodylia', family: 'Alligatoridae', diet: 'Carnivore' },
    { name: 'Spectacled Caiman', sci: 'Caiman crocodilus', group: 'Reptile', iucn: 'LC', gbif_key: '2441434', order: 'Crocodylia', family: 'Alligatoridae', diet: 'Carnivore' },
    { name: 'Cuvier’s Dwarf Caiman', sci: 'Paleosuchus palpebrosus', group: 'Reptile', iucn: 'LC', gbif_key: '2441444', order: 'Crocodylia', family: 'Alligatoridae', diet: 'Carnivore' },
    { name: 'Yellow-footed Tortoise', sci: 'Chelonoidis denticulatus', group: 'Reptile', iucn: 'VU', gbif_key: '2441880', order: 'Testudines', family: 'Testudinidae', diet: 'Herbivore' },
    { name: 'Red-footed Tortoise', sci: 'Chelonoidis carbonarius', group: 'Reptile', iucn: 'LC', gbif_key: '2441879', order: 'Testudines', family: 'Testudinidae', diet: 'Herbivore' },
    { name: 'Arrau Turtle (Giant South American Turtle)', sci: 'Podocnemis expansa', group: 'Reptile', iucn: 'CD', gbif_key: '2442223', order: 'Testudines', family: 'Podocnemididae', diet: 'Herbivore' },
    { name: 'Matamata', sci: 'Chelus fimbriata', group: 'Reptile', iucn: 'LC', gbif_key: '2442263', order: 'Testudines', family: 'Chelidae', diet: 'Piscivore' },
    { name: 'Gold Tegu', sci: 'Tupinambis teguixin', group: 'Reptile', iucn: 'LC', gbif_key: '2469493', order: 'Squamata', family: 'Teiidae', diet: 'Omnivore' },
    { name: 'Argentine Black and White Tegu', sci: 'Salvator merianae', group: 'Reptile', iucn: 'LC', gbif_key: '8092288', order: 'Squamata', family: 'Teiidae', diet: 'Omnivore' },
    { name: 'Neotropical Tree Boa', sci: 'Corallus hortulana', group: 'Reptile', iucn: 'LC', gbif_key: '5225964', order: 'Squamata', family: 'Boidae', diet: 'Carnivore' }
  ],

  'North America': [
    // Mammals (>=15 species)
    { name: 'Grizzly Bear (Brown Bear)', sci: 'Ursus arctos', group: 'Mammal', iucn: 'LC', gbif_key: '2433433', order: 'Carnivora', family: 'Ursidae', diet: 'Omnivore' },
    { name: 'American Black Bear', sci: 'Ursus americanus', group: 'Mammal', iucn: 'LC', gbif_key: '2433435', order: 'Carnivora', family: 'Ursidae', diet: 'Omnivore' },
    { name: 'Gray Wolf', sci: 'Canis lupus', group: 'Mammal', iucn: 'LC', gbif_key: '5219173', order: 'Carnivora', family: 'Canidae', diet: 'Carnivore' },
    { name: 'Cougar (Mountain Lion)', sci: 'Puma concolor couguar', group: 'Mammal', iucn: 'LC', gbif_key: '2435099', order: 'Carnivora', family: 'Felidae', diet: 'Carnivore' },
    { name: 'Bobcat', sci: 'Lynx rufus', group: 'Mammal', iucn: 'LC', gbif_key: '2435272', order: 'Carnivora', family: 'Felidae', diet: 'Carnivore' },
    { name: 'Canada Lynx', sci: 'Lynx canadensis', group: 'Mammal', iucn: 'LC', gbif_key: '2435275', order: 'Carnivora', family: 'Felidae', diet: 'Carnivore' },
    { name: 'Moose', sci: 'Alces alces', group: 'Mammal', iucn: 'LC', gbif_key: '2440932', order: 'Artiodactyla', family: 'Cervidae', diet: 'Herbivore' },
    { name: 'Elk (Wapiti)', sci: 'Cervus canadensis', group: 'Mammal', iucn: 'LC', gbif_key: '2440957', order: 'Artiodactyla', family: 'Cervidae', diet: 'Herbivore' },
    { name: 'White-tailed Deer', sci: 'Odocoileus virginianus', group: 'Mammal', iucn: 'LC', gbif_key: '2440965', order: 'Artiodactyla', family: 'Cervidae', diet: 'Herbivore' },
    { name: 'Mule Deer', sci: 'Odocoileus hemionus', group: 'Mammal', iucn: 'LC', gbif_key: '2440966', order: 'Artiodactyla', family: 'Cervidae', diet: 'Herbivore' },
    { name: 'American Bison', sci: 'Bison bison', group: 'Mammal', iucn: 'NT', gbif_key: '2441050', order: 'Artiodactyla', family: 'Bovidae', diet: 'Herbivore' },
    { name: 'Wolverine', sci: 'Gulo gulo', group: 'Mammal', iucn: 'LC', gbif_key: '2433857', order: 'Carnivora', family: 'Mustelidae', diet: 'Carnivore' },
    { name: 'North American Beaver', sci: 'Castor canadensis', group: 'Mammal', iucn: 'LC', gbif_key: '2437637', order: 'Rodentia', family: 'Castoridae', diet: 'Herbivore' },
    { name: 'North American Porcupine', sci: 'Erethizon dorsatum', group: 'Mammal', iucn: 'LC', gbif_key: '2437599', order: 'Rodentia', family: 'Erethizontidae', diet: 'Herbivore' },
    { name: 'Raccoon', sci: 'Procyon lotor', group: 'Mammal', iucn: 'LC', gbif_key: '5218786', order: 'Carnivora', family: 'Procyonidae', diet: 'Omnivore' },
    { name: 'River Otter', sci: 'Lontra canadensis', group: 'Mammal', iucn: 'LC', gbif_key: '2433649', order: 'Carnivora', family: 'Mustelidae', diet: 'Piscivore' },

    // Birds (>=25 species)
    { name: 'Bald Eagle', sci: 'Haliaeetus leucocephalus', group: 'Bird', iucn: 'LC', gbif_key: '2480449', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Piscivore' },
    { name: 'Golden Eagle', sci: 'Aquila chrysaetos', group: 'Bird', iucn: 'LC', gbif_key: '2480508', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'Great Horned Owl', sci: 'Bubo virginianus', group: 'Bird', iucn: 'LC', gbif_key: '2497678', order: 'Strigiformes', family: 'Strigidae', diet: 'Carnivore' },
    { name: 'Barred Owl', sci: 'Strix varia', group: 'Bird', iucn: 'LC', gbif_key: '2497615', order: 'Strigiformes', family: 'Strigidae', diet: 'Carnivore' },
    { name: 'Pileated Woodpecker', sci: 'Dryocopus pileatus', group: 'Bird', iucn: 'LC', gbif_key: '2477838', order: 'Piciformes', family: 'Picidae', diet: 'Insectivore' },
    { name: 'Red-tailed Hawk', sci: 'Buteo jamaicensis', group: 'Bird', iucn: 'LC', gbif_key: '2480537', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'Cooper’s Hawk', sci: 'Accipiter cooperii', group: 'Bird', iucn: 'LC', gbif_key: '2480614', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'Blue Jay', sci: 'Cyanocitta cristata', group: 'Bird', iucn: 'LC', gbif_key: '2482596', order: 'Passeriformes', family: 'Corvidae', diet: 'Omnivore' },
    { name: 'Steller’s Jay', sci: 'Cyanocitta stelleri', group: 'Bird', iucn: 'LC', gbif_key: '2482594', order: 'Passeriformes', family: 'Corvidae', diet: 'Omnivore' },
    { name: 'Common Raven', sci: 'Corvus corax', group: 'Bird', iucn: 'LC', gbif_key: '2482489', order: 'Passeriformes', family: 'Corvidae', diet: 'Omnivore' },
    { name: 'Black-capped Chickadee', sci: 'Poecile atricapillus', group: 'Bird', iucn: 'LC', gbif_key: '2487807', order: 'Passeriformes', family: 'Paridae', diet: 'Granivore' },
    { name: 'Tufted Titmouse', sci: 'Baeolophus bicolor', group: 'Bird', iucn: 'LC', gbif_key: '2487829', order: 'Passeriformes', family: 'Paridae', diet: 'Insectivore' },
    { name: 'Northern Cardinal', sci: 'Cardinalis cardinalis', group: 'Bird', iucn: 'LC', gbif_key: '2490384', order: 'Passeriformes', family: 'Cardinalidae', diet: 'Granivore' },
    { name: 'Scarlet Tanager', sci: 'Piranga olivacea', group: 'Bird', iucn: 'LC', gbif_key: '2488402', order: 'Passeriformes', family: 'Cardinalidae', diet: 'Insectivore' },
    { name: 'Wood Duck', sci: 'Aix sponsa', group: 'Bird', iucn: 'LC', gbif_key: '2498389', order: 'Anseriformes', family: 'Anatidae', diet: 'Herbivore' },
    { name: 'Wild Turkey', sci: 'Meleagris gallopavo', group: 'Bird', iucn: 'LC', gbif_key: '2473979', order: 'Galliformes', family: 'Phasianidae', diet: 'Omnivore' },
    { name: 'Ruffed Grouse', sci: 'Bonasa umbellus', group: 'Bird', iucn: 'LC', gbif_key: '2473587', order: 'Galliformes', family: 'Phasianidae', diet: 'Herbivore' },
    { name: 'Belted Kingfisher', sci: 'Megaceryle alcyon', group: 'Bird', iucn: 'LC', gbif_key: '2475525', order: 'Coraciiformes', family: 'Alcedinidae', diet: 'Piscivore' },
    { name: 'Cedar Waxwing', sci: 'Bombycilla cedrorum', group: 'Bird', iucn: 'LC', gbif_key: '2484439', order: 'Passeriformes', family: 'Bombycillidae', diet: 'Frugivore' },
    { name: 'Hermit Thrush', sci: 'Catharus guttatus', group: 'Bird', iucn: 'LC', gbif_key: '2490827', order: 'Passeriformes', family: 'Turdidae', diet: 'Omnivore' },
    { name: 'American Robin', sci: 'Turdus migratorius', group: 'Bird', iucn: 'LC', gbif_key: '2490715', order: 'Passeriformes', family: 'Turdidae', diet: 'Omnivore' },
    { name: 'Great Blue Heron', sci: 'Ardea herodias', group: 'Bird', iucn: 'LC', gbif_key: '2480931', order: 'Pelecaniformes', family: 'Ardeidae', diet: 'Piscivore' },
    { name: 'Green Heron', sci: 'Butorides virescens', group: 'Bird', iucn: 'LC', gbif_key: '2480860', order: 'Pelecaniformes', family: 'Ardeidae', diet: 'Piscivore' },
    { name: 'Osprey', sci: 'Pandion haliaetus', group: 'Bird', iucn: 'LC', gbif_key: '2480766', order: 'Accipitriformes', family: 'Pandionidae', diet: 'Piscivore' },
    { name: 'Ruby-throated Hummingbird', sci: 'Archilochus colubris', group: 'Bird', iucn: 'LC', gbif_key: '2476140', order: 'Apodiformes', family: 'Trochilidae', diet: 'Nectarivore' },

    // Reptiles (>=18 species)
    { name: 'American Alligator', sci: 'Alligator mississippiensis', group: 'Reptile', iucn: 'LC', gbif_key: '2441441', order: 'Crocodylia', family: 'Alligatoridae', diet: 'Carnivore' },
    { name: 'Timber Rattlesnake', sci: 'Crotalus horridus', group: 'Reptile', iucn: 'LC', gbif_key: '2470677', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'Eastern Diamondback Rattlesnake', sci: 'Crotalus adamanteus', group: 'Reptile', iucn: 'LC', gbif_key: '2470685', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'Copperhead', sci: 'Agkistrodon contortrix', group: 'Reptile', iucn: 'LC', gbif_key: '2470744', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'Cottonmouth (Water Moccasin)', sci: 'Agkistrodon piscivorus', group: 'Reptile', iucn: 'LC', gbif_key: '2470743', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'Eastern Rat Snake', sci: 'Pantherophis alleghaniensis', group: 'Reptile', iucn: 'LC', gbif_key: '8221663', order: 'Squamata', family: 'Colubridae', diet: 'Carnivore' },
    { name: 'Corn Snake', sci: 'Pantherophis guttatus', group: 'Reptile', iucn: 'LC', gbif_key: '2456073', order: 'Squamata', family: 'Colubridae', diet: 'Carnivore' },
    { name: 'Common Garter Snake', sci: 'Thamnophis sirtalis', group: 'Reptile', iucn: 'LC', gbif_key: '2457223', order: 'Squamata', family: 'Colubridae', diet: 'Carnivore' },
    { name: 'Eastern Box Turtle', sci: 'Terrapene carolina', group: 'Reptile', iucn: 'VU', gbif_key: '2442436', order: 'Testudines', family: 'Emydidae', diet: 'Omnivore' },
    { name: 'Common Snapping Turtle', sci: 'Chelydra serpentina', group: 'Reptile', iucn: 'LC', gbif_key: '2441951', order: 'Testudines', family: 'Chelydridae', diet: 'Omnivore' },
    { name: 'Painted Turtle', sci: 'Chrysemys picta', group: 'Reptile', iucn: 'LC', gbif_key: '2442385', order: 'Testudines', family: 'Emydidae', diet: 'Omnivore' },
    { name: 'Gopher Tortoise', sci: 'Gopherus polyphemus', group: 'Reptile', iucn: 'VU', gbif_key: '2441857', order: 'Testudines', family: 'Testudinidae', diet: 'Herbivore' },
    { name: 'Green Anole', sci: 'Anolis carolinensis', group: 'Reptile', iucn: 'LC', gbif_key: '2467145', order: 'Squamata', family: 'Dactyloidae', diet: 'Insectivore' },
    { name: 'Eastern Fence Lizard', sci: 'Sceloporus undulatus', group: 'Reptile', iucn: 'LC', gbif_key: '2466035', order: 'Squamata', family: 'Phrynosomatidae', diet: 'Insectivore' },
    { name: 'Broad-headed Skink', sci: 'Plestiodon laticeps', group: 'Reptile', iucn: 'LC', gbif_key: '5226145', order: 'Squamata', family: 'Scincidae', diet: 'Insectivore' },
    { name: 'Five-lined Skink', sci: 'Plestiodon fasciatus', group: 'Reptile', iucn: 'LC', gbif_key: '5226147', order: 'Squamata', family: 'Scincidae', diet: 'Insectivore' },
    { name: 'Coachwhip', sci: 'Masticophis flagellum', group: 'Reptile', iucn: 'LC', gbif_key: '2456722', order: 'Squamata', family: 'Colubridae', diet: 'Carnivore' },
    { name: 'Northern Watersnake', sci: 'Nerodia sipedon', group: 'Reptile', iucn: 'LC', gbif_key: '2457497', order: 'Squamata', family: 'Colubridae', diet: 'Piscivore' }
  ],

  Europe: [
    // Mammals (>=15 species)
    { name: 'Eurasian Brown Bear', sci: 'Ursus arctos arctos', group: 'Mammal', iucn: 'LC', gbif_key: '2433433', order: 'Carnivora', family: 'Ursidae', diet: 'Omnivore' },
    { name: 'Eurasian Wolf', sci: 'Canis lupus lupus', group: 'Mammal', iucn: 'LC', gbif_key: '5219173', order: 'Carnivora', family: 'Canidae', diet: 'Carnivore' },
    { name: 'Eurasian Lynx', sci: 'Lynx lynx', group: 'Mammal', iucn: 'LC', gbif_key: '2435282', order: 'Carnivora', family: 'Felidae', diet: 'Carnivore' },
    { name: 'European Wildcat', sci: 'Felis silvestris', group: 'Mammal', iucn: 'LC', gbif_key: '2435039', order: 'Carnivora', family: 'Felidae', diet: 'Carnivore' },
    { name: 'Red Deer', sci: 'Cervus elaphus', group: 'Mammal', iucn: 'LC', gbif_key: '2440954', order: 'Artiodactyla', family: 'Cervidae', diet: 'Herbivore' },
    { name: 'European Roe Deer', sci: 'Capreolus capreolus', group: 'Mammal', iucn: 'LC', gbif_key: '2440962', order: 'Artiodactyla', family: 'Cervidae', diet: 'Herbivore' },
    { name: 'European Fallow Deer', sci: 'Dama dama', group: 'Mammal', iucn: 'LC', gbif_key: '2440941', order: 'Artiodactyla', family: 'Cervidae', diet: 'Herbivore' },
    { name: 'Wild Boar', sci: 'Sus scrofa', group: 'Mammal', iucn: 'LC', gbif_key: '2441214', order: 'Artiodactyla', family: 'Suidae', diet: 'Omnivore' },
    { name: 'European Badger', sci: 'Meles meles', group: 'Mammal', iucn: 'LC', gbif_key: '2433878', order: 'Carnivora', family: 'Mustelidae', diet: 'Omnivore' },
    { name: 'Red Fox', sci: 'Vulpes vulpes', group: 'Mammal', iucn: 'LC', gbif_key: '5219243', order: 'Carnivora', family: 'Canidae', diet: 'Omnivore' },
    { name: 'Pine Marten', sci: 'Martes martes', group: 'Mammal', iucn: 'LC', gbif_key: '2433807', order: 'Carnivora', family: 'Mustelidae', diet: 'Carnivore' },
    { name: 'European Beaver', sci: 'Castor fiber', group: 'Mammal', iucn: 'LC', gbif_key: '2437640', order: 'Rodentia', family: 'Castoridae', diet: 'Herbivore' },
    { name: 'Red Squirrel', sci: 'Sciurus vulgaris', group: 'Mammal', iucn: 'LC', gbif_key: '2437500', order: 'Rodentia', family: 'Sciuridae', diet: 'Herbivore' },
    { name: 'European Hedgehog', sci: 'Erinaceus europaeus', group: 'Mammal', iucn: 'LC', gbif_key: '2437142', order: 'Eulipotyphla', family: 'Erinaceidae', diet: 'Insectivore' },
    { name: 'Alpine Chamois', sci: 'Rupicapra rupicapra', group: 'Mammal', iucn: 'LC', gbif_key: '2441094', order: 'Artiodactyla', family: 'Bovidae', diet: 'Herbivore' },
    { name: 'European Bison (Wisent)', sci: 'Bison bonasus', group: 'Mammal', iucn: 'NT', gbif_key: '2441052', order: 'Artiodactyla', family: 'Bovidae', diet: 'Herbivore' },

    // Birds (>=25 species)
    { name: 'Golden Eagle', sci: 'Aquila chrysaetos', group: 'Bird', iucn: 'LC', gbif_key: '2480508', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'White-tailed Eagle', sci: 'Haliaeetus albicilla', group: 'Bird', iucn: 'LC', gbif_key: '2480455', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Piscivore' },
    { name: 'Eurasian Eagle-Owl', sci: 'Bubo bubo', group: 'Bird', iucn: 'LC', gbif_key: '2497677', order: 'Strigiformes', family: 'Strigidae', diet: 'Carnivore' },
    { name: 'Tawny Owl', sci: 'Strix aluco', group: 'Bird', iucn: 'LC', gbif_key: '2497619', order: 'Strigiformes', family: 'Strigidae', diet: 'Carnivore' },
    { name: 'Black Woodpecker', sci: 'Dryocopus martius', group: 'Bird', iucn: 'LC', gbif_key: '2477833', order: 'Piciformes', family: 'Picidae', diet: 'Insectivore' },
    { name: 'Great Spotted Woodpecker', sci: 'Dendrocopos major', group: 'Bird', iucn: 'LC', gbif_key: '2477914', order: 'Piciformes', family: 'Picidae', diet: 'Insectivore' },
    { name: 'Common Buzzard', sci: 'Buteo buteo', group: 'Bird', iucn: 'LC', gbif_key: '2480544', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'Eurasian Sparrowhawk', sci: 'Accipiter nisus', group: 'Bird', iucn: 'LC', gbif_key: '2480628', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'Eurasian Jay', sci: 'Garrulus glandarius', group: 'Bird', iucn: 'LC', gbif_key: '2482455', order: 'Passeriformes', family: 'Corvidae', diet: 'Omnivore' },
    { name: 'Eurasian Nuthatch', sci: 'Sitta europaea', group: 'Bird', iucn: 'LC', gbif_key: '2484920', order: 'Passeriformes', family: 'Sittidae', diet: 'Insectivore' },
    { name: 'European Robin', sci: 'Erithacus rubecula', group: 'Bird', iucn: 'LC', gbif_key: '2492582', order: 'Passeriformes', family: 'Muscicapidae', diet: 'Insectivore' },
    { name: 'Song Thrush', sci: 'Turdus philomelos', group: 'Bird', iucn: 'LC', gbif_key: '2490740', order: 'Passeriformes', family: 'Turdidae', diet: 'Omnivore' },
    { name: 'Eurasian Blackbird', sci: 'Turdus merula', group: 'Bird', iucn: 'LC', gbif_key: '2490779', order: 'Passeriformes', family: 'Turdidae', diet: 'Omnivore' },
    { name: 'Great Tit', sci: 'Parus major', group: 'Bird', iucn: 'LC', gbif_key: '2487854', order: 'Passeriformes', family: 'Paridae', diet: 'Insectivore' },
    { name: 'Eurasian Blue Tit', sci: 'Cyanistes caeruleus', group: 'Bird', iucn: 'LC', gbif_key: '2487848', order: 'Passeriformes', family: 'Paridae', diet: 'Insectivore' },
    { name: 'Common Chaffinch', sci: 'Fringilla coelebs', group: 'Bird', iucn: 'LC', gbif_key: '2494396', order: 'Passeriformes', family: 'Fringillidae', diet: 'Granivore' },
    { name: 'European Greenfinch', sci: 'Chloris chloris', group: 'Bird', iucn: 'LC', gbif_key: '7341893', order: 'Passeriformes', family: 'Fringillidae', diet: 'Granivore' },
    { name: 'Eurasian Bullfinch', sci: 'Pyrrhula pyrrhula', group: 'Bird', iucn: 'LC', gbif_key: '2494361', order: 'Passeriformes', family: 'Fringillidae', diet: 'Granivore' },
    { name: 'Common Wood Pigeon', sci: 'Columba palumbus', group: 'Bird', iucn: 'LC', gbif_key: '2495368', order: 'Columbiformes', family: 'Columbidae', diet: 'Granivore' },
    { name: 'European Turtle Dove', sci: 'Streptopelia turtur', group: 'Bird', iucn: 'VU', gbif_key: '2495679', order: 'Columbiformes', family: 'Columbidae', diet: 'Granivore' },
    { name: 'Common Cuckoo', sci: 'Cuculus canorus', group: 'Bird', iucn: 'LC', gbif_key: '2496256', order: 'Cuculiformes', family: 'Cuculidae', diet: 'Insectivore' },
    { name: 'Eurasian Hoopoe', sci: 'Upupa epops', group: 'Bird', iucn: 'LC', gbif_key: '2498453', order: 'Bucerotiformes', family: 'Upupidae', diet: 'Insectivore' },
    { name: 'European Bee-eater', sci: 'Merops apiaster', group: 'Bird', iucn: 'LC', gbif_key: '2475586', order: 'Coraciiformes', family: 'Meropidae', diet: 'Insectivore' },
    { name: 'European Roller', sci: 'Coracias garrulus', group: 'Bird', iucn: 'LC', gbif_key: '2475738', order: 'Coraciiformes', family: 'Coraciidae', diet: 'Insectivore' },
    { name: 'Western Capercaillie', sci: 'Tetrao urogallus', group: 'Bird', iucn: 'LC', gbif_key: '2473489', order: 'Galliformes', family: 'Phasianidae', diet: 'Herbivore' },

    // Reptiles (>=18 species)
    { name: 'Common European Adder', sci: 'Vipera berus', group: 'Reptile', iucn: 'LC', gbif_key: '2470792', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'Nose-horned Viper', sci: 'Vipera ammodytes', group: 'Reptile', iucn: 'LC', gbif_key: '2470797', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'Asp Viper', sci: 'Vipera aspis', group: 'Reptile', iucn: 'LC', gbif_key: '2470791', order: 'Squamata', family: 'Viperidae', diet: 'Carnivore' },
    { name: 'Grass Snake', sci: 'Natrix natrix', group: 'Reptile', iucn: 'LC', gbif_key: '2455913', order: 'Squamata', family: 'Colubridae', diet: 'Amphibians, fish' },
    { name: 'Barred Grass Snake', sci: 'Natrix helvetica', group: 'Reptile', iucn: 'LC', gbif_key: '9785532', order: 'Squamata', family: 'Colubridae', diet: 'Amphibians, fish' },
    { name: 'Dice Snake', sci: 'Natrix tessellata', group: 'Reptile', iucn: 'LC', gbif_key: '2455916', order: 'Squamata', family: 'Colubridae', diet: 'Piscivore' },
    { name: 'Aesculapian Snake', sci: 'Zamenis longissimus', group: 'Reptile', iucn: 'LC', gbif_key: '2456481', order: 'Squamata', family: 'Colubridae', diet: 'Carnivore' },
    { name: 'Smooth Snake', sci: 'Coronella austriaca', group: 'Reptile', iucn: 'LC', gbif_key: '2456396', order: 'Squamata', family: 'Colubridae', diet: 'Carnivore' },
    { name: 'Western Green Lizard', sci: 'Lacerta bilineata', group: 'Reptile', iucn: 'LC', gbif_key: '2469085', order: 'Squamata', family: 'Lacertidae', diet: 'Insectivore' },
    { name: 'Eastern Green Lizard', sci: 'Lacerta viridis', group: 'Reptile', iucn: 'LC', gbif_key: '2469074', order: 'Squamata', family: 'Lacertidae', diet: 'Insectivore' },
    { name: 'Sand Lizard', sci: 'Lacerta agilis', group: 'Reptile', iucn: 'LC', gbif_key: '2469072', order: 'Squamata', family: 'Lacertidae', diet: 'Insectivore' },
    { name: 'Viviparous Lizard (Common Lizard)', sci: 'Zootoca vivipara', group: 'Reptile', iucn: 'LC', gbif_key: '2469046', order: 'Squamata', family: 'Lacertidae', diet: 'Insectivore' },
    { name: 'Common Wall Lizard', sci: 'Podarcis muralis', group: 'Reptile', iucn: 'LC', gbif_key: '2469145', order: 'Squamata', family: 'Lacertidae', diet: 'Insectivore' },
    { name: 'Slow Worm', sci: 'Anguis fragilis', group: 'Reptile', iucn: 'LC', gbif_key: '2468352', order: 'Squamata', family: 'Anguidae', diet: 'Slugs, worms' },
    { name: 'European Pond Turtle', sci: 'Emys orbicularis', group: 'Reptile', iucn: 'NT', gbif_key: '2442475', order: 'Testudines', family: 'Emydidae', diet: 'Carnivore' },
    { name: 'Hermann’s Tortoise', sci: 'Testudo hermanni', group: 'Reptile', iucn: 'NT', gbif_key: '2441868', order: 'Testudines', family: 'Testudinidae', diet: 'Herbivore' },
    { name: 'Marginated Tortoise', sci: 'Testudo marginata', group: 'Reptile', iucn: 'LC', gbif_key: '2441869', order: 'Testudines', family: 'Testudinidae', diet: 'Herbivore' },
    { name: 'Moorish Gecko', sci: 'Tarentola mauritanica', group: 'Reptile', iucn: 'LC', gbif_key: '2468453', order: 'Squamata', family: 'Phyllodactylidae', diet: 'Insectivore' }
  ],

  Oceania: [
    // Mammals (>=15 species)
    { name: 'Koala', sci: 'Phascolarctos cinereus', group: 'Mammal', iucn: 'VU', gbif_key: '2440003', order: 'Diprotodontia', family: 'Phascolarctidae', diet: 'Folivore' },
    { name: 'Red Kangaroo', sci: 'Osphranter rufus', group: 'Mammal', iucn: 'LC', gbif_key: '10746685', order: 'Diprotodontia', family: 'Macropodidae', diet: 'Herbivore' },
    { name: 'Eastern Grey Kangaroo', sci: 'Macropus giganteus', group: 'Mammal', iucn: 'LC', gbif_key: '2440049', order: 'Diprotodontia', family: 'Macropodidae', diet: 'Herbivore' },
    { name: 'Platypus', sci: 'Ornithorhynchus anatinus', group: 'Mammal', iucn: 'NT', gbif_key: '2433290', order: 'Monotremata', family: 'Ornithorhynchidae', diet: 'Carnivore' },
    { name: 'Short-beaked Echidna', sci: 'Tachyglossus aculeatus', group: 'Mammal', iucn: 'LC', gbif_key: '2433297', order: 'Monotremata', family: 'Tachyglossidae', diet: 'Insectivore' },
    { name: 'Tasmanian Devil', sci: 'Sarcophilus harrisii', group: 'Mammal', iucn: 'EN', gbif_key: '2435345', order: 'Dasyuromorphia', family: 'Dasyuridae', diet: 'Carnivore' },
    { name: 'Common Brushtail Possum', sci: 'Trichosurus vulpecula', group: 'Mammal', iucn: 'LC', gbif_key: '2440008', order: 'Diprotodontia', family: 'Phalangeridae', diet: 'Folivore' },
    { name: 'Sugar Glider', sci: 'Petaurus breviceps', group: 'Mammal', iucn: 'LC', gbif_key: '2440018', order: 'Diprotodontia', family: 'Petauridae', diet: 'Omnivore' },
    { name: 'Common Wombat', sci: 'Vombatus ursinus', group: 'Mammal', iucn: 'LC', gbif_key: '2440000', order: 'Diprotodontia', family: 'Vombatidae', diet: 'Herbivore' },
    { name: 'Quokka', sci: 'Setonix brachyurus', group: 'Mammal', iucn: 'VU', gbif_key: '2440058', order: 'Diprotodontia', family: 'Macropodidae', diet: 'Herbivore' },
    { name: 'Dingo', sci: 'Canis lupus dingo', group: 'Mammal', iucn: 'VU', gbif_key: '5219173', order: 'Carnivora', family: 'Canidae', diet: 'Carnivore' },
    { name: 'Tiger Quoll', sci: 'Dasyurus maculatus', group: 'Mammal', iucn: 'NT', gbif_key: '2435360', order: 'Dasyuromorphia', family: 'Dasyuridae', diet: 'Carnivore' },
    { name: 'Tree Kangaroo', sci: 'Dendrolagus lumholtzi', group: 'Mammal', iucn: 'NT', gbif_key: '2440032', order: 'Diprotodontia', family: 'Macropodidae', diet: 'Folivore' },
    { name: 'Bilby (Greater Bilby)', sci: 'Macrotis lagotis', group: 'Mammal', iucn: 'VU', gbif_key: '2435384', order: 'Peramelemorphia', family: 'Thylacomyidae', diet: 'Omnivore' },
    { name: 'Swamp Wallaby', sci: 'Wallabia bicolor', group: 'Mammal', iucn: 'LC', gbif_key: '2440061', order: 'Diprotodontia', family: 'Macropodidae', diet: 'Herbivore' },
    { name: 'Grey-headed Flying Fox', sci: 'Pteropus poliocephalus', group: 'Mammal', iucn: 'VU', gbif_key: '2433060', order: 'Chiroptera', family: 'Pteropodidae', diet: 'Frugivore' },

    // Birds (>=25 species)
    { name: 'Laughing Kookaburra', sci: 'Dacelo novaeguineae', group: 'Bird', iucn: 'LC', gbif_key: '2475661', order: 'Coraciiformes', family: 'Alcedinidae', diet: 'Carnivore' },
    { name: 'Southern Cassowary', sci: 'Casuarius casuarius', group: 'Bird', iucn: 'LC', gbif_key: '2474945', order: 'Casuariiformes', family: 'Casuariidae', diet: 'Frugivore' },
    { name: 'Emu', sci: 'Dromaius novaehollandiae', group: 'Bird', iucn: 'LC', gbif_key: '2474936', order: 'Casuariiformes', family: 'Dromaiidae', diet: 'Omnivore' },
    { name: 'Superb Lyrebird', sci: 'Menura novaehollandiae', group: 'Bird', iucn: 'LC', gbif_key: '2488880', order: 'Passeriformes', family: 'Menuridae', diet: 'Insectivore' },
    { name: 'Sulphur-crested Cockatoo', sci: 'Cacatua galerita', group: 'Bird', iucn: 'LC', gbif_key: '2479426', order: 'Psittaciformes', family: 'Cacatuidae', diet: 'Granivore' },
    { name: 'Galah', sci: 'Eolophus roseicapilla', group: 'Bird', iucn: 'LC', gbif_key: '2479440', order: 'Psittaciformes', family: 'Cacatuidae', diet: 'Granivore' },
    { name: 'Rainbow Lorikeet', sci: 'Trichoglossus moluccanus', group: 'Bird', iucn: 'LC', gbif_key: '8066736', order: 'Psittaciformes', family: 'Psittaculidae', diet: 'Nectarivore' },
    { name: 'Australian Magpie', sci: 'Gymnorhina tibicen', group: 'Bird', iucn: 'LC', gbif_key: '2494273', order: 'Passeriformes', family: 'Artamidae', diet: 'Insectivore' },
    { name: 'Wedge-tailed Eagle', sci: 'Aquila audax', group: 'Bird', iucn: 'LC', gbif_key: '2480509', order: 'Accipitriformes', family: 'Accipitridae', diet: 'Carnivore' },
    { name: 'Tawny Frogmouth', sci: 'Podargus strigoides', group: 'Bird', iucn: 'LC', gbif_key: '2496739', order: 'Caprimulgiformes', family: 'Podargidae', diet: 'Carnivore' },
    { name: 'Superb Fairywren', sci: 'Malurus cyaneus', group: 'Bird', iucn: 'LC', gbif_key: '2487508', order: 'Passeriformes', family: 'Maluridae', diet: 'Insectivore' },
    { name: 'Crimson Rosella', sci: 'Platycercus elegans', group: 'Bird', iucn: 'LC', gbif_key: '2479338', order: 'Psittaciformes', family: 'Psittaculidae', diet: 'Granivore' },
    { name: 'Eastern Rosella', sci: 'Platycercus eximius', group: 'Bird', iucn: 'LC', gbif_key: '2479339', order: 'Psittaciformes', family: 'Psittaculidae', diet: 'Granivore' },
    { name: 'Satin Bowerbird', sci: 'Ptilonorhynchus violaceus', group: 'Bird', iucn: 'LC', gbif_key: '2488884', order: 'Passeriformes', family: 'Ptilonorhynchidae', diet: 'Frugivore' },
    { name: 'Australian King Parrot', sci: 'Alisterus scapularis', group: 'Bird', iucn: 'LC', gbif_key: '2479261', order: 'Psittaciformes', family: 'Psittaculidae', diet: 'Frugivore' },
    { name: 'Red-browed Finch', sci: 'Neochmia temporalis', group: 'Bird', iucn: 'LC', gbif_key: '2493774', order: 'Passeriformes', family: 'Estrildidae', diet: 'Granivore' },
    { name: 'Willie Wagtail', sci: 'Rhipidura leucophrys', group: 'Bird', iucn: 'LC', gbif_key: '2486638', order: 'Passeriformes', family: 'Rhipiduridae', diet: 'Insectivore' },
    { name: 'Noisy Miner', sci: 'Manorina melanocephala', group: 'Bird', iucn: 'LC', gbif_key: '2487216', order: 'Passeriformes', family: 'Meliphagidae', diet: 'Nectarivore' },
    { name: 'Little Penguin', sci: 'Eudyptula minor', group: 'Bird', iucn: 'LC', gbif_key: '2481639', order: 'Sphenisciformes', family: 'Spheniscidae', diet: 'Piscivore' },
    { name: 'North Island Brown Kiwi', sci: 'Apteryx mantelli', group: 'Bird', iucn: 'VU', gbif_key: '2474324', order: 'Apterygiformes', family: 'Apterygidae', diet: 'Invertebrates' },
    { name: 'Kea', sci: 'Nestor notabilis', group: 'Bird', iucn: 'EN', gbif_key: '2479669', order: 'Psittaciformes', family: 'Strigopidae', diet: 'Omnivore' },
    { name: 'Kākā', sci: 'Nestor meridionalis', group: 'Bird', iucn: 'EN', gbif_key: '2479670', order: 'Psittaciformes', family: 'Strigopidae', diet: 'Frugivore' },
    { name: 'Tūī', sci: 'Prosthemadera novaeseelandiae', group: 'Bird', iucn: 'LC', gbif_key: '2487002', order: 'Passeriformes', family: 'Meliphagidae', diet: 'Nectarivore' },
    { name: 'New Zealand Fantail', sci: 'Rhipidura fuliginosa', group: 'Bird', iucn: 'LC', gbif_key: '2486634', order: 'Passeriformes', family: 'Rhipiduridae', diet: 'Insectivore' },
    { name: 'Paradise Shelduck', sci: 'Tadorna variegata', group: 'Bird', iucn: 'LC', gbif_key: '2498263', order: 'Anseriformes', family: 'Anatidae', diet: 'Herbivore' },

    // Reptiles (>=18 species)
    { name: 'Saltwater Crocodile', sci: 'Crocodylus porosus', group: 'Reptile', iucn: 'LC', gbif_key: '2441421', order: 'Crocodylia', family: 'Crocodylidae', diet: 'Carnivore' },
    { name: 'Freshwater Crocodile', sci: 'Crocodylus johnstoni', group: 'Reptile', iucn: 'LC', gbif_key: '2441419', order: 'Crocodylia', family: 'Crocodylidae', diet: 'Piscivore' },
    { name: 'Eastern Blue-tongued Lizard', sci: 'Tiliqua scincoides', group: 'Reptile', iucn: 'LC', gbif_key: '2468341', order: 'Squamata', family: 'Scincidae', diet: 'Omnivore' },
    { name: 'Central Bearded Dragon', sci: 'Pogona vitticeps', group: 'Reptile', iucn: 'LC', gbif_key: '2465365', order: 'Squamata', family: 'Agamidae', diet: 'Omnivore' },
    { name: 'Eastern Water Dragon', sci: 'Intellagama lesueurii', group: 'Reptile', iucn: 'LC', gbif_key: '7392687', order: 'Squamata', family: 'Agamidae', diet: 'Omnivore' },
    { name: 'Frilled Lizard', sci: 'Chlamydosaurus kingii', group: 'Reptile', iucn: 'LC', gbif_key: '2465362', order: 'Squamata', family: 'Agamidae', diet: 'Insectivore' },
    { name: 'Thorny Devil', sci: 'Moloch horridus', group: 'Reptile', iucn: 'LC', gbif_key: '2465377', order: 'Squamata', family: 'Agamidae', diet: 'Myrmecophage' },
    { name: 'Lace Monitor', sci: 'Varanus varius', group: 'Reptile', iucn: 'LC', gbif_key: '2470827', order: 'Squamata', family: 'Varanidae', diet: 'Carnivore' },
    { name: 'Perentie', sci: 'Varanus giganteus', group: 'Reptile', iucn: 'LC', gbif_key: '2470829', order: 'Squamata', family: 'Varanidae', diet: 'Carnivore' },
    { name: 'Sand Goanna', sci: 'Varanus gouldii', group: 'Reptile', iucn: 'LC', gbif_key: '2470825', order: 'Squamata', family: 'Varanidae', diet: 'Carnivore' },
    { name: 'Inland Taipan', sci: 'Oxyuranus microlepidotus', group: 'Reptile', iucn: 'LC', gbif_key: '2470477', order: 'Squamata', family: 'Elapidae', diet: 'Carnivore' },
    { name: 'Coastal Taipan', sci: 'Oxyuranus scutellatus', group: 'Reptile', iucn: 'LC', gbif_key: '2470478', order: 'Squamata', family: 'Elapidae', diet: 'Carnivore' },
    { name: 'Eastern Brown Snake', sci: 'Pseudonaja textilis', group: 'Reptile', iucn: 'LC', gbif_key: '2470534', order: 'Squamata', family: 'Elapidae', diet: 'Carnivore' },
    { name: 'Tiger Snake', sci: 'Notechis scutatus', group: 'Reptile', iucn: 'LC', gbif_key: '2470498', order: 'Squamata', family: 'Elapidae', diet: 'Carnivore' },
    { name: 'Red-bellied Black Snake', sci: 'Pseudechis porphyriacus', group: 'Reptile', iucn: 'LC', gbif_key: '2470528', order: 'Squamata', family: 'Elapidae', diet: 'Carnivore' },
    { name: 'Carpet Python', sci: 'Morelia spilota', group: 'Reptile', iucn: 'LC', gbif_key: '2465053', order: 'Squamata', family: 'Pythonidae', diet: 'Carnivore' },
    { name: 'Green Tree Python', sci: 'Morelia viridis', group: 'Reptile', iucn: 'LC', gbif_key: '2465057', order: 'Squamata', family: 'Pythonidae', diet: 'Carnivore' },
    { name: 'Tuatara', sci: 'Sphenodon punctatus', group: 'Reptile', iucn: 'LC', gbif_key: '2468356', order: 'Rhynchocephalia', family: 'Sphenodontidae', diet: 'Invertebrates, small reptiles' }
  ]
};

REGIONAL_FAUNA_CATALOG['Global'] = REGIONAL_FAUNA_CATALOG['Asia'];
